name: Step3 Combine sketches

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "refseq version"
        required: true
      run0:
        description: "mash sketch run"
        required: true
      run1:
        description: "mash sketch run"
        required: true
      run2:
        description: "mash sketch run"
        required: true
      run3:
        description: "mash sketch run"
        required: true
      run4:
        description: "mash sketch run"
        required: true
      run5:
        description: "mash sketch run"
        required: true
      run6:
        description: "mash sketch run"
        required: true
      run7:
        description: "mash sketch run"
        required: true
      run8:
        description: "mash sketch run"
        required: true

run-name: Combine sketches for ${{ github.event.inputs.version }}

jobs:
  pull_together:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@master
        with:
          lfs: true
        
      - name: Download the sketch from run 0
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run0 }}

      - name: Download the sketch from run 1
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run1 }}

      - name: Download the sketch from run 2
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run2 }}

      - name: Download the sketch from run 3
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run3 }}

      - name: Download the sketch from run 4
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run4 }}

      - name: Download the sketch from run 5
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run5 }}

      - name: Download the sketch from run 6
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run6 }}

      - name: Download the sketch from run 7
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run7 }}

      - name: Download the sketch from run 8
        uses: actions/download-artifact@v4
        with:
          pattern: "*_sketch"
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run8 }}

      - name: remove old file
        run: rm data/RefSeqSketches*msh*

      - name: Download Mash version 2.3
        run: |
          wget -q https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar
          rm -rf mash-Linux64-v2.3.tar
          mv mash-Linux64-v2.3 mash

      - name: paste_together
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          ls
          ls *_sketch
          mash paste data/RefSeqSketches_${{ github.event.inputs.version }} *_sketch/*.msh
          rm -rf *_sketch

      - name: Compress Sketch
        run: gzip data/RefSeqSketches_${{ github.event.inputs.version }}.msh

      - name: Remove Mash
        run: rm -rf mash

      - name: Create LFS tracked file
        run: |
          git lfs track data/RefSeqSketches_*msh.gz

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
            commit-message: Update mash reference to ${{ github.event.inputs.version }}
            title: Update mash reference to ${{ github.event.inputs.version }}
            body: |
              - mash reference for RefSeq version ${{ github.event.inputs.version }}
  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-mash
