name: Combine sketches

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "refseq version"
        required: true

run-name: Combine sketches for ${{ github.event.inputs.version }}

jobs:
  pull_together:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repository
        uses: actions/checkout@master

      - name: Download sketches
        uses: actions/download-artifact@v4
        with:
          pattern: "*${{ github.event.inputs.version }}_sketch"

      - name: remove old file
        run: rm data/RefSeqSketches*msh*

      - name: Download Mash version 2.3
        run: |
          wget https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar
          rm -rf mash-Linux64-v2.3.tar
          mv mash-Linux64-v2.3 mash

      - name: paste_together
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          ls
          ls *_${{ github.event.inputs.version }}_sketch
          mash paste data/RefSeqSketches_${{ github.event.inputs.version }} *_${{ github.event.inputs.version }}_sketch/*_${{ github.event.inputs.version }}.msh
          rm -rf *_${{ github.event.inputs.version }}_sketch

      - name: Compress Sketch
        run: gzip data/RefSeqSketches_${{ github.event.inputs.version }}.msh

      - name: Remove Mash
        run: rm -rf mash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
            commit-message: Update mash reference to ${{ github.event.inputs.version }}
            title: Update mash reference to ${{ github.event.inputs.version }}
            body: |
              - mash reference for RefSeq version ${{ github.event.inputs.version }}
  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-mash

      
          
