name: Create Reference

on: [workflow_dispatch, workflow_call]

run-name: Create Reference

jobs:

  install_datasets:
    uses: ./.github/workflows/install_datasets.yml

  install_mash:
    uses: ./.github/workflows/install_mash.yml

  download_reference_genomes:
    needs: [install_datasets, install_mash]
    runs-on: ubuntu-20.04
    steps:
      - name: check software
        run: |
          ls
