name: Create Reference

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "refseq version"
        required: true

run-name: Create Reference

jobs:
  download_reference_genomes:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repository
        uses: actions/checkout@master
      
      - name: Download Datasets and Dataformat
        run: |
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
          chmod +x datasets dataformat

      - name: Download Mash version 2.3
        run: |
          wget https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar
          rm -rf mash-Linux64-v2.3.tar
          mv mash-Linux64-v2.3 mash

      - name: remove old file
        run: rm data/RefSeqSketches*msh*

      - name: check software
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          ls
          mash -h
          datasets

      - name: get genome list
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          mkdir -p data
          cd data
          datasets summary genome taxon bacteria --reference --as-json-lines | \
            dataformat tsv genome --fields accession,organism-name --elide-header | \
            head -n 25 |
            sed 's/\[//g' | \
            sed 's/\]//g' | \
            sed 's/["'\'']//g' | \
            sed 's/endosymbiont of /endosymbiont_of_/g' > \
            ids.txt
          
      - name: work some magic
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          cd data
          while read line
          do
            id=$(echo $line | awk '{print $1}')
            ge=$(echo $line | awk '{print $2}')
            if [ ! -n "$ge" ] ; then ge="unknown" ; fi
            sp=$(echo $line | awk '{print $3}')
            if [ ! -n "$sp" ] ; then sp="unknown" ; fi
            
            echo "preparing $id $ge $sp"

            datasets download genome accession $id
            unzip ncbi_dataset.zip
            cp ncbi_dataset/data/*/*_genomic.fna ${ge}_${sp}_${id}.fasta
            if [ ! -f RefSeqSketches_${{ github.event.inputs.version }}.msh ]
            then
              mash sketch ${ge}_${sp}_${id}.fasta -o RefSeqSketches_${{ github.event.inputs.version }}
            else          
              mash sketch ${ge}_${sp}_${id}.fasta -o ${ge}_${sp}_${id}
              mv RefSeqSketches_${{ github.event.inputs.version }}.msh tmp.msh
              mash paste RefSeqSketches_${{ github.event.inputs.version }} tmp.msh ${ge}_${sp}_${id}.msh
              rm tmp.msh ${ge}_${sp}_${id}.msh
              ls -alh RefSeqSketches_${{ github.event.inputs.version }}.msh
            fi
            rm ${ge}_${sp}_${id}.fasta
            rm -rf ncbi_dataset/
            rm ncbi_dataset.zip
            rm README.md
            rm md5sum.txt
          done < ids.txt

      - name: Compress Sketch
        run: |
          cd data
          gzip RefSeqSketches_${{ github.event.inputs.version }}.msh

      - name: Remove Mash and Datasets
        run: |
          rm -rf mash/
          rm datasets
          rm dataformat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
            commit-message: Update mash reference to ${{ github.event.inputs.version }}
            title: Update mash reference to ${{ github.event.inputs.version }}
            body: |
              - mash reference for RefSeq version ${{ github.event.inputs.version }}
  
              Auto-generated by [create-pull-request][1]
  
              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-mash

      
          
