name: Step2 Create Sketches

on: 
  workflow_dispatch:
    inputs:
      run:
        description: run id for reference creation
        required: true
      chunk:
        description: "chunk of ids.txt to work on [00-08]"
        required: true

run-name: Create sketch for chunk ${{ github.event.inputs.chunk }} from ${{ github.event.inputs.run }}

jobs:          
  download_and_sketch:
    runs-on: ubuntu-20.04
    steps:
      - name: Download the ids
        uses: actions/download-artifact@v4
        with:
          name: genome-split-files
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run }}
      
      - name: Download Datasets and Dataformat
        run: |
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
          chmod +x datasets dataformat

      - name: Download Mash version 2.3
        run: |
          wget -q https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar
          rm -rf mash-Linux64-v2.3.tar
          mv mash-Linux64-v2.3 mash

      - name: Check files
        run: ls 

      - name: work some magic
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          mkdir tmp
          cd tmp
          
          while read line
          do
            id=$(echo $line | awk '{print $1}')
            ge=$(echo $line | awk '{print $2}')
            if [ ! -n "$ge" ] ; then ge="unknown" ; fi
            sp=$(echo $line | awk '{print $3}')
            if [ ! -n "$sp" ] ; then sp="unknown" ; fi
            
            j=0
            while [ $j -lt 1 ]
            do
              j=2
              date
              echo "downloading $id $ge $sp genome"
              datasets download genome accession $id --no-progressbar || { date ; echo "Couldn't download. Sleeping and tyring again" ; sleep 15s ; j=0 }
            done

            date
            echo "download complete!"
            echo "copying file"
            unzip ncbi_dataset.zip
            cp ncbi_dataset/data/*/*_genomic.fna ${ge}_${sp}_${id}.fasta

            date
            if [ ! -f "final.msh" ]
            then
              echo "creating initial mash sketch"
              mash sketch ${ge}_${sp}_${id}.fasta -o final
            else
              echo "creating mash sketch"
              mash sketch ${ge}_${sp}_${id}.fasta -o sample
              mv final.msh tmp.msh

              date
              echo "pasting mash sketches"
              mash paste final tmp.msh sample.msh
              rm tmp.msh sample.msh
            fi

            ls -alh final.msh

            date
            echo "sketching complete! removing extra files"
            rm -rf ${ge}_${sp}_${id}.fasta ncbi_dataset/ ncbi_dataset.zip README.md md5sum.txt
          done < ../x${{ github.event.inputs.chunk }}.txt

          mv final.msh ${{ github.event.inputs.chunk }}.msh

      - name: Upload sketch
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.chunk }}_sketch
          path: tmp/${{ github.event.inputs.chunk }}.msh
          overwrite: true
