name: Create Reference

on: [workflow_dispatch, workflow_call]

run-name: Create Reference

jobs:
  download_reference_genomes:
    runs-on: ubuntu-20.04
    steps:
      - name: Download Datasets and Dataformat
        run: |
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
          chmod +x datasets dataformat

      - name: Download Mash version 2.3
        run: |
          wget https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar
          rm -rf mash-Linux64-v2.3.tar
          mv mash-Linux64-v2.3 mash

      - name: check software
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          ls
          mash -h
          datasets

      - name: get genome list
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          datasets summary genome taxon bacteria --reference --as-json-lines | \
            dataformat tsv genome --fields accession,organism-name --elide-header | \
            sed 's/\[//g' | \
            sed 's/\]//g' | \
            sed 's/["'\'']//g' | \
            sed 's/\./_/g' | \
            sed 's/endosymbiont of /endosymbiont_of_/g' | \
            head -n 25 > \
            ids.txt
          
      - name: work some magic
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          while read line
          do
            id=$(echo $line | awk '{print $1}')
            ge=$(echo $line | awk '{print $2}')
            if [ ! -n "$ge" ] ; then ge="unknown" ; fi
            sp=$(echo $line | awk '{print $3}')
            if [ ! -n "$sp" ] ; then sp="unknown" ; fi
            
            echo "preparing $id $ge $sp"

            datasets download genome accession $id
            unzip ncbi_dataset.zip
            cp ncbi_dataset/data/*/*_genomic.fna ${ge}_${sp}_${id}.fasta
            if [ ! -f all.msh ]
            then
              mash sketch ${ge}_${sp}_${id}.fasta -o all
            else          
              mash sketch ${ge}_${sp}_${id}.fasta -o ${ge}_${sp}_${id}
              mv all.msh tmp.msh
              mash paste all tmp.msh ${ge}_${sp}_${id}.msh
              rm tmp.msh ${ge}_${sp}_${id}.msh
              ls -alh all.msh
            fi
            rm ${ge}_${sp}_${id}.fasta
            rm -rf ncbi_dataset*
          done < ids.txt

      
          
