name: Step1 Create Reference

on: 
  workflow_dispatch:

run-name: Create reference list

jobs:
  list_reference_genomes:
    runs-on: ubuntu-20.04
    steps:
      - name: Download Datasets and Dataformat
        run: |
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
          chmod +x datasets dataformat

      - name: check software
        run: |
          export PATH=$(pwd):$(pwd)/:$PATH
          ls
          datasets

      - name: get genome list
        run: |
          export PATH=$(pwd):$(pwd)/mash:$PATH
          datasets summary genome taxon bacteria --reference --as-json-lines | \
            dataformat tsv genome --fields accession,organism-name --elide-header | \
            sed 's/\[//g' | \
            sed 's/\]//g' | \
            sed 's/["'\'']//g' | \
            sed 's/endosymbiont of /endosymbiont_of_/g' > \
            ids.txt

      - name: check size
        run: |
          genomes=$(wc -l ids.txt | awk '{print $1}')
          wc -l ids.txt
          echo "There are ${genomes} genomes in id.txt"
          # head -n 25 ids.txt > ids.tmp
          # mv ids.tmp ids.txt
          # if [ $genomes -lt 19700 ] ; then cd doesntexist ; fi

      - name: split file
        run: |
          split -n  l/9 ids.txt -d --additional-suffix=.txt
          ls x*txt

      - name: Upload split files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: genome-split-files
          path: x*.txt
          overwrite: true
