name: Install Datasets

on: [workflow_dispatch, workflow_call]

run-name: Install Datasets

jobs:

  datasets:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
          
      - name: Download Datasets and Dataformat
        run: |
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          wget https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
          chmod +x datasets dataformat
